- .github/workflows/build.yml
- Bencodex/Bencodex.csproj
- azure-pipelines.yml
Automated process to deploy. It will deploy development version, too.
> Automate deploy

- .github/workflows/build.yml
- Bencodex/Bencodex.csproj
- CHANGES.md
- Release 0.2.0.
- Every push will be automatically deployed, even if it wasn't on master.
> Release 0.2.0

- Bencodex/Bencodex.csproj
- CHANGES.md
> Ready to 0.3.0

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
It's related with #6 but this includes only *proposal 1*.
it's to prevent too bigger pull-request size.
> High-level API to build dictionaries

- Bencodex.Tests.ruleset
- Bencodex.Tests/Bencodex.Tests.csproj
- Bencodex.Tests/CodecTest.cs
- Bencodex.Tests/Misc/ByteArrayComparerTest.cs
- Bencodex.Tests/Misc/ByteChunkQueueTest.cs
- Bencodex.Tests/Misc/CompositeComparerTest.cs
- Bencodex.Tests/Spec.cs
- Bencodex.Tests/SpecData.cs
- Bencodex.Tests/SpecTheoryData.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex.ruleset
- Bencodex/Bencodex.csproj
- Bencodex/Codec.cs
- Bencodex/CodecException.cs
- Bencodex/DecodingException.cs
- Bencodex/Misc/ByteArrayComparer.cs
- Bencodex/Misc/ByteChunkQueue.cs
- Bencodex/Misc/CompositeComparer.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IKey.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Text.cs
- stylecop.json
Applied `StyleCop.Analyzers` and update codes to follow the rule.
Also fixed language version to *7.2*.
> Introduce StyleCop.Analyzers

- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex/Types/Binary.cs
- CHANGES.md
Please read added logs in the *CHANGES.md* file.
> Add Binary(string, Encoding) constructor and fix a Binary's unintended mutability

- Bencodex.Tests/Extensions.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- azure-pipelines.yml
> Fix broken ListTest.Inspect() on Windows

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
Added:
-  `Bencodex.Types.Dictionary.ContainsKey(string)`
-  `Bencodex.Types.Dictionary.ContainsKey(byte[])`
> Extend Bencodex.Types.Dictionary.ContainsKey

- .github/workflows/build.yml
- Bencodex.Tests/Spec.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex/Codec.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Integer.cs
- CHANGES.md
> Fix coding bugs occurred on some locales writing RTL scripts

- .github/workflows/build.yml
- Bencodex.Tests/Bencodex.Tests.csproj
- Bencodex/Bencodex.csproj
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/Text.cs
- CHANGES.md
See also the changelog for details.
> Introduce C# 8, .NET Standard 2.1, and nullable references

- Bencodex/Misc/ByteArrayComparer.cs
- Bencodex/Misc/CompositeComparer.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/CommonVariables.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Text.cs
It improves its encoding performance.
> refactor: optimize encoding

- .gitignore
- Bencodex.Tests/Bencodex.Tests.csproj
- Bencodex.Tests/Types/NullTest.cs
- Bencodex/Types/Null.cs
- CHANGES.md
The title says it all.  Addresses the issue <https://github.com/planetarium/bencodex.net/issues/20>.
> Make `Null` a read-only struct & add `Null.Value` read-only field

- .github/workflows/build.yml
> ci(gh-actions): use timestamp as suffix

- .github/workflows/build.yml
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
Closes <https://github.com/planetarium/bencodex.net/issues/19>.
> Make `IValue` to inherit `IEquatable<IValue>`

- .github/workflows/build.yml
- CHANGES.md
As we haven't released for a long time, it's time to make a new one.
> Release 0.3.0

- CHANGES.md
> 🚀 Release 0.5.0

- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.6.0

- CHANGES.md
> 🚀 Release 0.6.0

- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.7.0

- CHANGES.md
> Release 0.7.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> Prepare 0.8.0

- CHANGES.md
> 🚀 Release 0.8.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.9.0

- CHANGES.md
> 🚀 Release 0.9.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.10.0

- CHANGES.md
> 🚀 Release 0.10.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.11.0

- CHANGES.md
> 🚀 Release 0.11.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.12.0

- Bencodex/Decoder.cs
- Bencodex/Types/Binary.cs
Just grabbing some low hanging fruits.
> ⚡ Use `Array.Empty`

- CHANGES.md
> 🚀 Release 0.12.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.13.0

- CHANGES.md
Comprehensive benchmark comparison:
|           Method | SetSize | WordSize |        Mean |     Error |    StdDev |  Allocated |
|----------------- |-------- |--------- |------------:|----------:|----------:|-----------:|
|       DecodeList |      10 |       10 |    16.33 ms |  0.939 ms |  1.005 ms |   33.26 MB |
|       DecodeDict |      10 |       10 |    53.58 ms |  3.509 ms |  4.041 ms |   73.69 MB |
| DecodeNestedList |      10 |       10 |   163.18 ms |  8.270 ms |  9.524 ms |  336.54 MB |
| DecodeNestedDict |      10 |       10 |   574.93 ms | 24.271 ms | 27.951 ms |  781.33 MB |
|           Method | SetSize | WordSize |        Mean |     Error |    StdDev | Allocated |
|----------------- |-------- |--------- |------------:|----------:|----------:|----------:|
|       DecodeList | …
> 🚀 Release 0.13.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.14.0

- CHANGES.md
> 🚀 Release 0.14.0

- Bencodex.Tests/Types/IntegerTest.cs
- Bencodex/Types/Integer.cs
- CHANGES.md
See #104 and #106 for more context.
> Streamline `Integer` equality and comparison

- CHANGES.md
> 🚀 Release 0.15.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.16.0

- CHANGES.md
> 🚀 Release 0.16.0

- Bencodex.Json/Bencodex.Json.csproj
- Bencodex/Bencodex.csproj
- CHANGES.md
> 🔧 Prepare 0.17.0
