- .github/workflows/build.yml
The build workflow hadn't worked as well on tag pushed.
In my thought, it's because `GITHUB_REF` format is like `refs/tags/0.1.0`,  not `/refs/tags/0.1.0`.
So I fixed it.
> Fix typo in build workflow

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
I skipped the changelog since 0.3.0 hasn't released yet. This resolves #10.
> Fix Dictionary.Add(byte[], IEnumerable<IValue>)

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
- azure-pipelines.yml
This adds `Inspection` property to `IValue` in order to resolve #12.  This looks like JSON, and with no `Binary` values it's indeed virtually JSON, for `Binary` values it's printed as a string of hex-escaped bytes with `b` prefix; in other words, it's like Python's `repr()`.
For example, <https://github.com/planetarium/bencodex/blob/1.2/testsuite/mixed-dict.dat> is turned into:
```python
{
"a": 1,
"á": 2,
"á": 5,
"b": 3,
"c": 4,
b"\x61": 1,
b"\x62": 2,
b"\x63": 3
}
```
Another example, <https://github.com/planetarium/bencodex/blob/1.2/testsuite/list-of-dicts.dat>, becomes:
```python
[
{
"byte-string": true,
"human-readable": false,
"name": "bencode",
"normalization": true,
"schema": false,
"unicode-text": false,
"zero-copy": false
},
{
"byte-string": true,
"human-readable": false, …
```
> IValue.Inspection: JSON-like human-readable representation

- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/List.cs
- CHANGES.md
Fixes that the below line was invalid with the message, *Cannot access explicit implementation of 'IReadOnlyList<IValue>.Item'*. 4af2ee6
```csharp
Bencodex.Types.List list = ...;
var item = list[0]; // ← this point
```
And also in `Bencodex.Types.List.Count`. 0857583
> Resolve explicit implementation issues on Bencodex.Types.List

- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/List.cs
- CHANGES.md
It contains overloads below:
- `Bencodex.Types.List.Add(IValue)`
- `Bencodex.Types.List.Add(bool)`
- `Bencodex.Types.List.Add(string)`
- `Bencodex.Types.List.Add(byte[])`
- `Bencodex.Types.List.Add(BigInteger)`
> Introduce `Bencodex.Types.List.Add(...)` API

- .gitignore
- Bencodex.Benchmarks/Bencodex.Benchmarks.csproj
- Bencodex.Benchmarks/CodecBenchmark.cs
- Bencodex.sln
You can conduct a benchmark in short through the following command:
```
dotnet run -c Release -p Bencodex.Benchmarks -- -j dry -i -f CodecBenchmark --iterationCount 1
```
In order to run it properly:
```
dotnet run -c Release -p Bencodex.Benchmarks -- -i -f CodecBenchmark
```
If you need to profile it using [`EventPipeProfiler`](https://benchmarkdotnet.org/articles/features/event-pipe-profiler.html):
```
dotnet run -c Release -p Bencodex.Benchmarks -- -j dry -i -f CodecBenchmark --iterationCount 1 -p EP
```
---
You can configure the custom data set using the `BENCODEX_BENCHMARKS_DATA_DIR` environment variable.
```bash
export BENCODEX_BENCHMARKS_DATA_DIR=$HOME/my-bencodex-data/
dotnet run -c Release -p Bencodex.Benchmarks -- -j dry -i -f CodecBenchmark --iterationCount 1
```
**Note that …
> Codec benchmarks

- Bencodex/Types/Text.cs
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading	00:00:00.0731935
Codec	00:00:24.9972116
Total	00:00:25.0704051
```
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading	00:00:00.0668352
Codec	00:00:21.4916718
Total	00:00:21.5585070
```
> refactor: inline Binary.EncodeIntoChunks()

- Bencodex/Decoder.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
Before:
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading	00:00:00.0850930
Decoding	00:00:09.6730710
Total	00:00:09.7581640
```
After:
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading	00:00:00.1089530
Decoding	00:00:04.9425080
Total	00:00:05.0514610
```
> Lazy dictionary realization

- Bencodex/Codec.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
This adds `IValue.EncodeToStream(Stream)` method and uses it to reduce the encoding time.
---
Before:
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading 00:00:00.0729370
Codec   00:00:18.4429740
Total   00:00:18.5159110
```
After:
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading 00:00:00.0775620
Codec   00:00:15.8652380
Total   00:00:15.9428000
```
> Add EncodeToStream

- Bencodex/Types/Dictionary.cs
- CHANGES.md
Continued from #34.  This make latency short when a `Dictionary` having unrealized internal pairs is enumerated.  The solution is to delay its realization and just enumerate its internal key–value pairs.  One trick here I used to avoid key duplication (note that unrealized keys don't guarantee their uniqueness) is simply comparing with the key from the previous iteration.  This trick works because the enumeration is done after keys are sorted first.
Before:
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading	00:00:00.1598300
Codec	00:00:15.4054540
Total	00:00:15.5652840
```
After:
```
Loading 50 files (102.26 MB = 102257499 bytes)...
Loaded 50 files.
Loading	00:00:00.1722320
Codec	00:00:08.1198900
Total	00:00:08.2921220
```
> Delay dictionary realization when it's enumerated

- Bencodex/Decoder.cs
- Bencodex/Types/Binary.cs
This PR fixes decode related methods and allocations to reduce the decoding time. Please see the commits as well.
---
Before:
```
Loading 00:00:00.0754400
Codec   00:00:09.3419490
Total   00:00:09.4173890
```
After:
```
Loading 00:00:00.0735380
Codec   00:00:07.6464170
Total   00:00:07.7199550
```
> Fix decode

- Bencodex/Decoder.cs
This fixes a bug that occurred when using the Decoder concurrently because the `TinyBuffer` was static.
> Fix TinyBuffer to be non-static

- Bencodex.Tests/Misc/ByteArrayComparerTest.cs
- Bencodex.Tests/Misc/ImplicitConversionTest.cs
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex/Misc/ByteArrayComparer.cs
- Bencodex/Types/Binary.cs
- CHANGES.md
In order to reduce unnecessary round-trips and memory copies, this patch rebased `Binary` on `ImmutableArray<byte>`.
> `ImmutableArray<byte>`-based `Binary`

- Bencodex/Types/Dictionary.cs
- CHANGES.md
As `Binary` is based on `ImmutableArray<byte>` instead of `byte[]` (see also #39), I added convenient method overloads for `ImmutableArray<byte>` on `Dictionary`.  These methods should be preferred over equivalent methods for `byte[]`, because they are more efficient (no unnecessary memory copy and no unnecessary round-trip).
> Convenient method overloads for `ImmutableArray<byte>` on `Dictionary`

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/List.cs
This patch adds trailing commas to `Dictionary.Inspection` & `List.Inspection`.  This is better for generating diffs between two `IValue.Inspection` trees.
Before:
```
[
"foo",
b"bar",
{
"baz": "qux",
"quux": 1234
},
null
]
```
After:
```
[
"foo",
b"bar",
{
"baz": "qux",
"quux": 1234,
},
null,
]
```
Diff:
```udiff
--- before	2021-10-01 10:51:29.000000000 +0900
+++ after	2021-10-01 10:51:26.000000000 +0900
@@ -1,9 +1,9 @@
[
"foo",
b"bar",
{
"baz": "qux",
-    "quux": 1234
+    "quux": 1234,
},
-  null
+  null,
]
```
> Trailing commas in multiline `Inspection` string

- Bencodex.Tests/CodecTest.cs
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/CommonVariables.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
In order to determine the number of encoded bytes of `IValue`s without actually encoding them, the `IValue.EncodingLength` property was introduced.
> Pre-calculated encoding length of values

- Bencodex.Tests/CodecTest.cs
- Bencodex.Tests/Extensions.cs
- Bencodex.Tests/Misc/FingerprintComparerTest.cs
- Bencodex.Tests/Misc/ImmutableByteArrayExtensionsTest.cs
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex.Tests/Types/BooleanTest.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/FingerprintTest.cs
- Bencodex.Tests/Types/IntegerTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex.Tests/Types/NullTest.cs
- Bencodex.Tests/Types/TextTest.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex/Misc/FingerprintComparer.cs
- Bencodex/Misc/ImmutableByteArrayExtensions.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Fingerprint.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- Bencodex/Types/ValueType.cs
- CHANGES.md
- README.md
Added `IValue.Fingerprint` for efficient tree comparison.
> Fingerprinting values for efficient tree comparison

- Bencodex.Benchmarks/ValueBenchmark.cs
- Bencodex.Tests/Misc/KeyComparerTest.cs
- Bencodex.Tests/TestUtils.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/FingerprintTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex.Tests/Types/ValueTests.cs
- Bencodex/Misc/KeyComparer.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Fingerprint.cs
- Bencodex/Types/List.cs
- CHANGES.md
This patch optimizes `List` and `Dictionary` types by refactoring them.
- Both types are now reference types.
- Every `Dictionary` instance is always sorted as [`ImmutableSortedDictionary<K, V>`][1] is used as its internal data structure.
- Due to this, I can get rid of its dual internal representations (`Dict` mode & `Pairs` mode) which were quite complicated.
|           Method |             DataFile |      Mean |    Error |    StdDev |
|----------------- |--------------------- |----------:|---------:|----------:|
|  EncodeIntoBytes | /tmp/(...)e.dat [96] | 27.853 ms | 3.870 ms | 0.2121 ms |
| EncodeIntoStream | /tmp/(...)e.dat [96] | 21.257 ms | 4.667 ms | 0.2558 ms |
|  DecodeFromBytes | /tmp/(...)e.dat [96] |  8.122 ms | 8.924 ms | 0.4891 ms |
| DecodeFromStream | /tmp/(...)e.dat …
> Optimize `List` & `Dictionary` types

- Bencodex.Tests/Misc/FingerprintComparerTest.cs
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex.Tests/Types/BooleanTest.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/FingerprintTest.cs
- Bencodex.Tests/Types/IndirectValueTest.cs
- Bencodex.Tests/Types/IntegerTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex.Tests/Types/NullTest.cs
- Bencodex.Tests/Types/TextTest.cs
- Bencodex/Misc/FingerprintComparer.cs
- Bencodex/Misc/KeyComparer.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Fingerprint.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/IndirectValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- Bencodex/Types/ValueKind.cs
- CHANGES.md
It is continued from the previous patch <https://github.com/planetarium/bencodex.net/pull/52>, and addresses <https://github.com/planetarium/bencodex.net/pull/52#pullrequestreview-810657314> in particular.
This patch simply makes `List` & `Dictionary` to expose its internal `IndirectValue`s so that loaded values and offloaded values are serialized/stored in different ways.
Plus, I renamed `ValueType` to `ValueKind` to disambiguate it from [`System.ValueType`][1].
[1]: https://docs.microsoft.com/en-us/dotnet/api/system.valuetype?view=netstandard-2.0
> Let `List`/`Dictionary` expose their `IndirectValue`s

- Bencodex/Codec.cs
- Bencodex/Encoder.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IKey.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
This patch fixes a regression made by <https://github.com/planetarium/bencodex.net/pull/49> that `Codec.Encode(IValue, Stream)` requires a stream to be seekable.  Now it accepts any readable streams again.
During this fix, I rewrote the whole encoding logic (so that it does not require streams to be seekable), and accidentally it became drastically faster than before.  Below strategies were applied:
- Instead of a lot of memory allocations for small chunks, it allocates the single long buffer with the exact length of the required bytes for the entire encoded representation.
- When it writes onto a stream, smaller chunks shorter than 4,096 bytes are grouped into a single chunk.
- Unnecessary memcpys were reduced using C#'s `in` keyword for parameters.
- Encoding methods became static in …
> Faster encoding: ×4 for `byte[]` & ×1,000 for `Stream`

- Bencodex.Tests/CodecTest.cs
- Bencodex.Tests/EncoderTest.cs
- Bencodex.Tests/TestUtils.cs
- Bencodex.Tests/Types/FingerprintTest.cs
- Bencodex.Tests/Types/IndirectValueTest.cs
- Bencodex.Tests/Types/IntegerTest.cs
- Bencodex/AssemblyInfo.cs
- Bencodex/Codec.cs
- Bencodex/Decoder.cs
- Bencodex/Encoder.cs
- Bencodex/IOffloadOptions.cs
- Bencodex/OffloadOptions.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/Fingerprint.cs
- Bencodex/Types/IndirectValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- CHANGES.md
*Continued from the pull request #52.*
This enable `Codec` to directly encode and decode offloaded values.  In serialized encoding, these offloaded values are represented as like (see also `EncoderTest.Offload()`):
- `2A` (ASCII `*`)[^1]
- the length of fingerprint bytes in ASCII decimal digits[^2]
- `3A` (ASCII `:`)
- fingerprint bytes[^3]
Note that this extended format is not included in the Bencodex spec.  It is currently just Bencodex.NET's own extension.  (Would it be addressed by the Bencodex spec?)
[^1]: This first one is a identifying byte among Bencodex's other identifiers like `i` (Integer), `l` (list).
[^2]: E.g., `31` `36` (ASCII `1` `6`) for 16-bytes fingerprint.
[^3]: It follows its own distinct encoding format, which was defined in the previous PR #50.  See also …
> Codec with offload options

- Bencodex.Tests/Bencodex.Tests.csproj
- Bencodex.Tests/OffloadInspectorTest.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Encoder.cs
- Bencodex/OffloadingInspector.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
The title says it all.  See also XML documents of `OffloadingInspector` static class.
This also includes a commit to fix the test project can be run on Apple Silicon (M1 series) with .NET 6.
> `OffloadingInspector` to show internal states of how containers offload their subtrees

- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/List.cs
This fixes bugs where `List` or `Dictionary` instances miss out their `Loader`.  As `IndirectValue` and `IndirectValue.Loader` are not released yet, changelogs are omitted.
> Fix bugs where containers miss out their loader

- .gitmodules
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/List.cs
- CHANGES.md
Resolves #58.
In general, redirections of `Add()` for type conversions and/or casting are done more systematically. For instance, when trying to add `(string, string)` to a `Dictionary`, the conversion path is
```
(string, string) -> (string, Text) -> (Text, Text) -> (Text, IValue) -> (IKey, IValue)
```
There could be a slight performance hit for certain cases, but in my opinion, this would make client-side code a lot easier to optimize and would probably increase overall performance.
For example, in the old scheme, when trying to add `(Text, Text)` to a dictionary, it is easy to make the following mistake.
```csharp
Text foo = new Text("foo");
Text bar = new Text("bar");
Dictionary dict = Dictionary.Empty.Add((string)foo, (string)bar);
```
As a result, explicit conversion from `Text` to …
> Additional type support

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
Pretty much a continuation of #63.
`Dictionary.SetItem()` overloads now mirror that of `Dictionary.Add()`. See #60 for the general redirection scheme.
> Additional type support for `Dictionary.SetItem()`

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/List.cs
- CHANGES.md
Still expanding on #58.
`Dictionary` and `List` supports more types directly. Additionally supported types generally mirror that of `Add()`.
- For a `List`, `new List(IEnumerable<T>)` is possible for those `T`s where `Add(T)` is allowed.
- For a `Dictionary`, `new Dictionary(IEnumerable<KeyValuePair<K, V>>)` is possible for those `K` and `V`s where `Add(K, V)` is allowed.
Whereas before we needed something like
```csharp
List<int> intList = new List<int> { 1, 2, 3 };
List list = new List(intList.Select(i => (IValue)(Integer)i));
```
this PR allows
```csharp
List<int> intList = new List<int> { 1, 2, 3 };
List list = new List(intList);
```
> Additional type support for `List` and `Dictionary` constructors

- Bencodex.Benchmarks/ValueBenchmark.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
Other than creating a new `List`, I don't think `IEnumerable<IValue>` is "primitive" enough to have its type supported for `Add()` and `SetItem()`. 🙄
> Drop support for `IEnumerable<IValue>` type parameter

- Bencodex/IBencodable.cs
- CHANGES.md
This is an attempt to prevent further fragmentation. This tries to address the following issues:
- Although the [bencodex.net] library is being used pretty heavily across the board, it isn't apparent from `class` or `struct` descriptor that such and such can be encoded to an `IValue`. It is only by usage and API that a certain `class` or `struct` can be encoded to an `IValue`.
- As there is no contract, the implementation for encoding and decoding between different `class`es differ wildly. In my opinion, users generally should not care about the underlying concrete type for the encoded `IValue`. That is, it should not be the user's responsibility to always know whether some piece of data as a generic `IValue` retrieved from some database should be a `List` or a `Dictionary` before …
> Introduce `IBencodable` interface

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/List.cs
- CHANGES.md
- Fixed `Bencodex.Types.Dictionary.GetHashCode()` to return consistent hashcode.
- Fixed `Bencodex.Types.List.GetHashCode()` to return consistent hashcode.
Applied `FNV-1 hash`, using `GetType().GetHashCode()` as `FNV_offset_basis`, and `397` as `FNV_prime`.
- https://github.com/planetarium/bencodex.net/issues/72
> Fix `getHashCode()` to be consistent

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/IndirectValueTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/IndirectValue.cs
- CHANGES.md
Previously, if there are two dictionaries like the below examples, their hashcode was the same. Because `Dictionary` has its key-value pairs as `KeyValuePair<IKey, IndirectValue>` type and `new IndirectValue((Integer)0).GetHashCode()` was the same with `new IndirectValue((Integer)1).GetHashCode()`
```
{ "type_id": 0 }
{ "type_id": 1 }
```
> Implement `IndirectValue.GetHashCode()`

- Bencodex/Encoder.cs
- CHANGES.md
Tested with 1,000,000 `long`s. Hot path for `Binary`, `Text` encoding.
Neither requires string conversion nor additional memory allocation. 😗
As for `Encoder.EncodeInteger()`, conversion from `BigInteger` to `long` seems heaver than `ToString()`, so it is left as it is. 😕
BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19045.3086)
11th Gen Intel Core i7-1185G7 3.00GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.203
[Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT AVX2
|   Method |     Mean |    Error |   StdDev |       Gen0 | Allocated |
|--------- |---------:|---------:|---------:|-----------:|----------:|
| GetBytes | 64.25 ms | 1.320 ms | 3.786 ms | 17800.0000 | 110.53 MB |
|  ForLoop | 42.02 ms | 0.840 ms | 2.396 ms | …
> ⚡ Optimized `Encoder.EncodeDigits()`

- Bencodex/Decoder.cs
- CHANGES.md
Companion PR to #83. Tested with 1,000,000 random `long`s up to 1024 (since for most cases, byte string and unicode string legths will be skewed towards the lower end).
Again, only deals with the length portion of byte strings and unicode strings.
|       Method |      Mean |     Error |    StdDev |       Gen0 |  Allocated |
|------------- |----------:|----------:|----------:|-----------:|-----------:|
|   ToLongAtoi | 20.875 ms | 0.4165 ms | 1.0898 ms | 11468.7500 | 72000015 B |
| ToLongDirect |  6.223 ms | 0.1236 ms | 0.2608 ms |          - |        4 B |
> ⚡ Optimized `Decoder`

- Bencodex/Decoder.cs
- CHANGES.md
Incorporates two following components:
- Less backtracking by avoiding peeking when it isn't necessary
- Returning `byte` instead of `byte?` for `ReadByte()` used for peeking.
Tested with data size of 10,000. Nested means one additional layer. For example, nested list would be a `List` of size `SetSize` with each element also being a `List` of size `SetSize`. Endpoints were randomized to be either `Binary` or `Text`.
Memory save is mostly from #91. Improves speed by roughly 20% on `List`s and `Dictionary`s.
|           Method | SetSize | WordSize |        Mean |     Error |    StdDev |  Allocated |
|----------------- |-------- |--------- |------------:|----------:|----------:|-----------:|
|       DecodeList |      10 |       10 |    16.33 ms |  0.939 ms |  1.005 ms |   33.26 MB |
| …
> ⚡ Optimize decoding with less backtracking

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Decoder.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
Resolves #92.
As a nice side-effect, this also optimizes decoding dictionaries.
If we already have wrongly encoded dictionary written into the network, this can be catastrophic. 🙄
The testing environment is as usual.
|           Method | SetSize | WordSize |        Mean |     Error |    StdDev |  Allocated |
|----------------- |-------- |--------- |------------:|----------:|----------:|-----------:|
|       DecodeDict |      10 |       10 |    42.57 ms |  4.061 ms |  4.514 ms |   56.82 MB |
| DecodeNestedDict |      10 |       10 |   439.78 ms | 23.726 ms | 27.323 ms |  596.64 MB |
|       DecodeDict |      20 |       10 |    85.96 ms |  5.403 ms |  6.222 ms |  105.61 MB |
| DecodeNestedDict |      20 |       10 | 1,777.23 ms | 51.972 ms | 57.767 ms | 2160.26 MB |
|           Method | …
> 🐛 ⚡ Fixed invalid decoding of dictionaries

- Bencodex.Tests/Types/IntegerTest.cs
- Bencodex/Decoder.cs
- CHANGES.md
In terms of performance, improvements are pretty minor. 🙄
However, there were bugs regarding decoding where invalid formats were allowed.  See the newly added test.
Cases 1, 3, and 4 fail on 0.13.0.
Tested with 100,000 encoded `Integer`s. `DecodeSmall` was generated using `Random.Next()` and `DecodeBig` was generated using `Random.NextInt64()`.
|      Method |     Mean |    Error |   StdDev |       Gen0 | Allocated |
|------------ |---------:|---------:|---------:|-----------:|----------:|
| DecodeSmall | 30.88 ms | 0.603 ms | 0.922 ms |  8500.0000 |  50.86 MB |
|   DecodeBig | 50.19 ms | 0.485 ms | 0.405 ms | 11500.0000 |  70.18 MB |
|      Method |     Mean |    Error |   StdDev |      Gen0 | Allocated |
|------------ |---------:|---------:|---------:|----------:|----------:|
| …
> ⚡ 🐛 Fix `Integer` decoding bug and optimize

- Bencodex/Decoder.cs
- CHANGES.md
Completely removes "backtracking" the internal `Stream`.
Yada yada, details as usual. 😗
|           Method | SetSize | WordSize |        Mean |     Error |    StdDev |  Allocated |
|----------------- |-------- |--------- |------------:|----------:|----------:|-----------:|
|       DecodeList |      10 |       10 |    11.69 ms |  0.546 ms |  0.607 ms |   21.51 MB |
|       DecodeDict |      10 |       10 |    31.25 ms |  1.672 ms |  1.926 ms |    39.9 MB |
| DecodeNestedList |      10 |       10 |   112.11 ms |  6.247 ms |  7.194 ms |  208.08 MB |
| DecodeNestedDict |      10 |       10 |   340.04 ms | 16.346 ms | 18.825 ms |  410.32 MB |
|           Method | SetSize | WordSize |         Mean |      Error |     StdDev |  Allocated |
|----------------- |-------- |--------- …
> ⚡ Completely remove back tracking

- Bencodex.Tests/Misc/ByteArrayComparerTest.cs
- Bencodex.Tests/Misc/ImplicitConversionTest.cs
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex/Misc/ByteArrayComparer.cs
- Bencodex/Types/Binary.cs
- CHANGES.md
Unlike `Integer` and `Text`, `Binary` equality/comparison have been modified to be *less* convenient.
- Equality of two `Binary` instances behave "as expected" (element-wise equality).
- No longer supports equality checking of `Binary`, `byte[]`, and `ImmutableArray<byte>`. The rationale being, one generally does not expect two array/list to be equal because the sequence of elements are the same. Generic equality usually refers to having the same reference for two objects. **This is pretty standard across many programming languages** including even javascript and python. Such functionality is generally provided by a separate method. 
- Another reason for the change mentioned above is that there is no way to implement **consistent** equality while providing the convenience(?) necessary due …
> Streamline `Binary` equality and comparison

- Bencodex.Tests/Types/ListTest.cs
- Bencodex/Types/List.cs
- CHANGES.md
This fixes similar problems present in #110 for `Binary`.
> Streamline `List` equality

- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
🧹 I'd say it's been obsoleted long enough. No longer seems to be used anywhere. 😶
> 🧹 Removed obsoleted field Inspection

- Bencodex.Tests/CodecTest.cs
- Bencodex.Tests/Types/BinaryTest.cs
- Bencodex.Tests/Types/BooleanTest.cs
- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex.Tests/Types/IntegerTest.cs
- Bencodex.Tests/Types/ListTest.cs
- Bencodex.Tests/Types/NullTest.cs
- Bencodex.Tests/Types/TextTest.cs
- Bencodex/Types/Binary.cs
- Bencodex/Types/Boolean.cs
- Bencodex/Types/Dictionary.cs
- Bencodex/Types/IValue.cs
- Bencodex/Types/Integer.cs
- Bencodex/Types/List.cs
- Bencodex/Types/Null.cs
- Bencodex/Types/Text.cs
- CHANGES.md
🧹 Since `Fingerprint` was removed in 0.15.0, there is no difference between `Inspect(true)` and `Inspect(false)` (which has always been the case as offloading was never used). 🙄
> 🧹 Removed unused parameter from Inspect()

- Bencodex.Tests/Types/BooleanTest.cs
- Bencodex/Types/Boolean.cs
- CHANGES.md
Forgot to do this in 0.15.0. 😥
> Streamline `Boolean` equality

- Bencodex.Tests/Types/DictionaryTest.cs
- Bencodex/Types/Dictionary.cs
- CHANGES.md
Few points:
- `GetValue<T>()` syntax was incomplete (relied on implicit casting of `Text` and `Binary`, which no longer works). `[]` syntax already does the job better.
- Didn't really provide much convenience. I'd say usage of `(T)[]` is more recommended than using `GetValue<T>()`
I've already removed all usage of `GetValue<T>()` from libplanet.
> 🧹 Remove `GetValue<T>()` from `Dictionary`

- Bencodex.Tests/EncoderTest.cs
- Bencodex/Encoder.cs
- CHANGES.md
Just squeezing out more performance. 🙄
Depending on the case, the speed gain seems to be about 20% ~ 30%.
On the memory side, the memory usage seems go down more drastically as the collection size gets bigger.
This is achieved through the following:
- Removed value argument passing and returning values for tracking the encoder state.
- Other than declaring temporary local variables, the global `offset` is tracked using a single variable using `ref`.
As a bonus, the code became more readable as well. Also a bug was fixed where an unused overloaded `Encode()` method was wrongly implemented (not sure if we still need to keep the method tho). 😗
|           Method | SetSize | WordSize |       Mean |      Error |     StdDev |       Gen0 | Allocated |
|----------------- |-------- |--------- …
> Optimized `Encoder.Encode()`
